config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  root to: "pages#home", as: :home
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end

  def contact
    @members = ["thanh", "dimitri", "germain", "damien", "julien"]

    if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<ul>
  <li><%=link_to "Home", home_path%></li>
  <li><%=link_to "About", about_path%></li>
  <li><%=link_to "Contact", contact_path%></li>
</ul>

app/views/pages/contact.html.erb
<h1>Contact page</h1>
<ul>
  <li><%=link_to "Home", home_path%></li>
  <li><%=link_to "About", about_path%></li>
  <li><%=link_to "Contact", contact_path%></li>
</ul>


<form action="/contact" method="get">
  <input type="text" name="member"  value="<%= params[:member] %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

app/views/pages/home.html.erb
<h1>Home page</h1>
<ul>
  <li><%= link_to "Home", home_path%></li>
  <li><%= link_to "About", about_path%></li>
  <li><%= link_to "Contact", contact_path%></li>
</ul>





<%# <%= link_to "about", "http://www.google.fr", target: :blank  %>


<%# <%= link_to about_path do %>
  <%# <img> %>
<%#end%>